### ISSUE TITLE
Integração com google maps para mostrar o lasallinho viajando de um país para outro

### ISSUE THREAD

**Issue by paulomotta** [ludica/LaSallinho#11]
Ao invés de desenharmos um mapa poderíamos usar o Google maps para mostrar inclusive as distâncias. Hoje em dia vários aplicativos fazem essa integração então seria uma coisa familiar para o usuário. Mas esse item não é obrigatório.

**Comment by ludica** [comment]
Por conta de mudança de tecnologia não poderá ser feito agora
